stages:
  - foundation:plan
  - foundation:apply
  - kubernetes:plan
  - kubernetes:apply

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_PASSWORD: ${GITLAB_TOKEN}

.plan:
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform init
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

.apply:
  script:
    - export | grep TF_
    - cd ${TF_ROOT}
    - gitlab-terraform init
    - gitlab-terraform apply
  artifacts:
    name: plan
  only:
    - main

foundation:plan:
  extends: .plan
  stage: foundation:plan
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/foundation
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-foundation
  

foundation:apply:
  extends: .apply
  stage: foundation:apply
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/foundation
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-foundation
  dependencies:
    - plan-foundation

kubernetes:plan:
  extends: .plan
  stage: kubernetes:plan
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/kubernetes
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-kubernetes
  

kubernetes:apply:
  extends: .apply
  stage: kubernetes:apply
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/kubernetes
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-kubernetes
  dependencies:
    - plan-kubernetes

