stages:
  - plan

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/azure
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/example-production
  
plan:
  stage: plan
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  script:
    # List all files in repo
    - export | grep TF_
    - 
