stages:
  - plan foundation
  - apply foundation
  - plan kubernetes
  - apply kubernetes

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_PASSWORD: ${GITLAB_TOKEN}

.plan:
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform init
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

.apply:
  script:
    - export | grep TF_
    - cd ${TF_ROOT}
    - gitlab-terraform init
    - gitlab-terraform apply
  artifacts:
    name: plan
  only:
    - main

plan foundation:
  extends: .plan
  stage: plan foundation
  resource_group: foundation
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/foundation
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-foundation
    TF_VAR_azure_subscription: $AZURE_SUBSCRIPTION_PRO

apply foundation:
  extends: .apply
  stage: apply foundation
  resource_group: foundation
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/foundation
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-foundation
    TF_VAR_azure_subscription: $AZURE_SUBSCRIPTION_PRO
  dependencies:
    - plan foundation

plan kubernetes:
  extends: .plan
  stage: plan kubernetes
  resource_group: kubernetes
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/kubernetes
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-kubernetes
    TF_VAR_azure_subscription: $AZURE_SUBSCRIPTION_ENTERPRISE_2
    TF_VAR_foundation_state_address: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-foundation

apply kubernetes:
  extends: .apply
  stage: apply kubernetes
  resource_group: kubernetes
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/azure/kubernetes
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-kubernetes
    TF_VAR_azure_subscription: $AZURE_SUBSCRIPTION_ENTERPRISE_2
    TF_VAR_foundation_state_address: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/azure-foundation
  dependencies:
    - plan kubernetes

